// <auto-generated />
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(EshopContext))]
    partial class EshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CategoryName = "Asp.Net Core",
                            Description = "Asp.Net Core 3"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Asp.Net MVC",
                            Description = "Asp.Net MVC 5"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "لباس ورزشی",
                            Description = "گروه لباس ورزشی"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "ساعت مچی",
                            Description = "گروه ساعت مچی"
                        });
                });

            modelBuilder.Entity("DataLayer.CategoryToProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryToProducts");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("DataLayer.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "در این دوره به مباحث پیشرفته ASP.NET MVC نیز خواهیم پرداخت",
                            ItemId = 1,
                            Name = "دوره آموزشی ASP.NET MVC پیشرفته"
                        },
                        new
                        {
                            Id = 2,
                            Description = "در این دوره به آموزش ASP.NET Core خواهیم پرداخت",
                            ItemId = 2,
                            Name = "دوره آموزشی ASP.NET Core "
                        },
                        new
                        {
                            Id = 3,
                            Description = "این لباس غواصی در برابر حملات کوسه ها مقاوم بوده و جان شما را حفظ میکند",
                            ItemId = 3,
                            Name = "لباس غواصی"
                        },
                        new
                        {
                            Id = 4,
                            Description = "این ساعت از جواهرات و الماس تزئین شده است",
                            ItemId = 4,
                            Name = "ساعت مچی رولکس"
                        });
                });

            modelBuilder.Entity("DataLayer.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("shopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 15000.0m,
                            QuantityInStock = 4
                        },
                        new
                        {
                            Id = 2,
                            Price = 25000.0m,
                            QuantityInStock = 21
                        },
                        new
                        {
                            Id = 3,
                            Price = 42000.0m,
                            QuantityInStock = 47
                        },
                        new
                        {
                            Id = 4,
                            Price = 10000.0m,
                            QuantityInStock = 22
                        });
                });

            modelBuilder.Entity("DataLayer.CategoryToProduct", b =>
                {
                    b.HasOne("DataLayer.Category", "Category")
                        .WithMany("categoryToProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Product", "Product")
                        .WithMany("CategoryToProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Product", b =>
                {
                    b.HasOne("DataLayer.ShopItem", "Item")
                        .WithOne("Product")
                        .HasForeignKey("DataLayer.Product", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
